binop_separator = "Front"
comment_width = 69
condense_wildcard_suffixes = true
edition = "2018"
empty_item_single_line = true
enum_discrim_align_threshold = 20
fn_args_layout = "Compressed"
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_strings = true
inline_attribute_width = 69
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 120
merge_imports = true
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
struct_field_align_threshold = 69
tab_spaces = 2
trailing_semicolon = true
use_field_init_shorthand = true
use_small_heuristics = "Max"
wrap_comments = true
